Docker - Etcd - C2D_RELEASE added into image (#23)
* Docker -Etcd - C2D_RELEASE added into image

* Docker -Etcd - C2D_RELEASE added into image

diff --git a/templates/Dockerfile.template b/templates/Dockerfile.template
--- a/templates/Dockerfile.template
+++ b/templates/Dockerfile.template
@@ -1,6 +1,7 @@
 # Update and install necessary packages
 {{- $etcd := index .Packages "etcd" }}
 {{- $golang := index .Packages "golang" }}
+{{- $c2dRelease := index .TemplateArgs "c2dRelease" }}
 
 FROM {{ .From }} as builder
 
@@ -28,6 +29,7 @@ ARG ETCD_VERSION={{ $etcd.Version }}
 ARG ETCD_SHA256=3f6b48d8c2844699f2b19c1880508ecf63e1489769ed37ebb97495d5cd848a89
 ENV ETCD_VER=${ETCD_VERSION}
 ENV ETCD_FILE=etcd.tar.gz
+ENV C2D_RELEASE {{ $c2dRelease }}
 
 # Download etcd source code and validate checksum
 RUN wget -q https://github.com/etcd-io/etcd/releases/download/v${ETCD_VER}/etcd-v${ETCD_VER}-linux-amd64.tar.gz -O ${ETCD_FILE} && \
@@ -67,6 +69,12 @@ RUN chmod +x /docker-entrypoint.sh
 
 ENV ETCD_DATA_DIR="/var/run/etcd/default.etcd"
 EXPOSE 2379 2380
+
+RUN etcd_version=$(etcd --version | grep 'etcd version' | cut -d ':' -f 2 | tr -d ' ') && \
+    if [ "${C2D_RELEASE}" != "${etcd_version}" ]; then \
+        echo "Version check failed"; \
+        exit 1; \
+    fi
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
 CMD ["etcd"]
