Add C2D_RELEASE env and tiny smoke test for version

diff --git a/templates/Dockerfile.template b/templates/Dockerfile.template
--- a/templates/Dockerfile.template
+++ b/templates/Dockerfile.template
@@ -53,6 +53,9 @@ RUN wget -q https://raw.githubusercontent.com/etcd-io/etcd/v${ETCD_VER}/LICENSE 
 ## Builded new "{{ .From }}" container will contain only files copied from Builder image
 FROM {{ .From }}
 
+
+ENV C2D_RELEASE={{ $etcd.Version }}
+
 RUN mkdir /usr/share/etcd
 
 COPY --from=builder /usr/local/bin/etcd /usr/local/bin/
@@ -63,6 +66,9 @@ COPY --from=builder /NOTICES /usr/share/etcd/NOTICES
 ENV ETCD_DATA_DIR="/var/run/etcd/default.etcd"
 
 COPY docker-entrypoint.sh /
+
+RUN test ${C2D_RELEASE} = $(/usr/local/bin/etcd --version | grep "etcd Version:" | cut -d: -f2) \
+         || { echo "Version check failed"; exit 1; }
 
 EXPOSE 2379 2380
 
