Docker - Etcd - C2D_RELEASE added into ENV (#24)
* Docker - etcd - C2D_RELEASE added into ENV

* Docker - etcd - C2D_RELEASE added into ENV

diff --git a/templates/Dockerfile.template b/templates/Dockerfile.template
--- a/templates/Dockerfile.template
+++ b/templates/Dockerfile.template
@@ -29,7 +29,6 @@ ARG ETCD_VERSION={{ $etcd.Version }}
 ARG ETCD_SHA256=3f6b48d8c2844699f2b19c1880508ecf63e1489769ed37ebb97495d5cd848a89
 ENV ETCD_VER=${ETCD_VERSION}
 ENV ETCD_FILE=etcd.tar.gz
-ENV C2D_RELEASE {{ $c2dRelease }}
 
 # Download etcd source code and validate checksum
 RUN wget -q https://github.com/etcd-io/etcd/releases/download/v${ETCD_VER}/etcd-v${ETCD_VER}-linux-amd64.tar.gz -O ${ETCD_FILE} && \
@@ -53,8 +52,10 @@ RUN wget -q https://github.com/etcd-io/etcd/releases/download/v${ETCD_VER}/etcd-
 # Download the release License
 RUN wget -q https://raw.githubusercontent.com/etcd-io/etcd/v${ETCD_VER}/LICENSE -O /LICENSE
 
-## Builded new "marketplace.gcr.io/google/c2d-debian11" container will contain only files copied from Builder imag
+## Builded new "marketplace.gcr.io/google/debian12" container will contain only files copied from Builder image
 FROM marketplace.gcr.io/google/debian12
+
+ENV C2D_RELEASE {{ $c2dRelease }}
 
 RUN apt-get update && \
     apt-get install -y libc-bin libssl3 && \
@@ -70,11 +71,8 @@ RUN chmod +x /docker-entrypoint.sh
 ENV ETCD_DATA_DIR="/var/run/etcd/default.etcd"
 EXPOSE 2379 2380
 
-RUN etcd_version=$(etcd --version | grep 'etcd version' | cut -d ':' -f 2 | tr -d ' ') && \
-    if [ "${C2D_RELEASE}" != "${etcd_version}" ]; then \
-        echo "Version check failed"; \
-        exit 1; \
-    fi
+RUN etcd_version=$(etcd --version | grep 'etcd Version:' | cut -d ' ' -f 3) && \
+    test "${C2D_RELEASE}" = "${etcd_version}" || { echo "Version check failed"; exit 1; }
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
 CMD ["etcd"]
